modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Low-Drag-MC/Shimmer/issues"

[[mods]]
modId="shimmer"
version="${version}"
displayName="Shimmer"
displayURL="https://github.com/Low-Drag-MC/Shimmer"
logoFile="logo_full.png"
credits="hypherionsa"
authors="KilaBash, zomb_676"
description='''Shimemr, make rendering vivid'''

[[mixins]]
config = "shimmer.mixins.json"
[[mixins]]
config = "shimmer.neoforge.mixins.json"

[[dependencies.shimmer]]
modId="neoforge"
type="required"
versionRange="[1,)"
ordering="NONE"
side="BOTH"

[[dependencies.shimmer]]
modId="minecraft"
type="required"
versionRange="[1.20.4,1.20.5)"
ordering="NONE"
side="BOTH"
